### PR TITLE
Rj42 actual coordinates

### PR DESCRIPTION
**Pull request by opticyclic**
Fix for https://github.com/zhuowei/RaspberryJuice/issues/42

Adds a Relative and Absolute option for coordinates and also adds an API to get and set absolute player position regardless of the config option.

### CODE REVIEW

**Comment by martinohanlon** [comment]
Thanks for the PR, Im away until the new year, so it'll be a couple of weeks till I look into it. :)

**Comment by martinohanlon** [comment]
There was a bug where integer (i.e. block / tile) positions where being returned as floats which was causing parsing errors within the python library.

I have changed the code to include a parseLocation method for integers here https://github.com/zhuowei/RaspberryJuice/blob/dev/src/main/java/net/zhuoweizhang/raspberryjuice/RemoteSession.java#L571  Do you agree with the fix?

An alternative implementation would have been to set `.origin` to Location(world, 0, 0, 0) if the location was absolute here https://github.com/zhuowei/RaspberryJuice/blob/dev/src/main/java/net/zhuoweizhang/raspberryjuice/RemoteSession.java#L98  Any thoughts? Is it worth changing?

**Comment by martinohanlon** [comment]
@opticyclic any thoughts on this?

**Comment by opticyclic** [comment]
If you changed `.origin` wouldn't that just make the coordinates relative to the new origin instead of absolute?

If `.origin` was set-able by the user scripts and didn't affect other players it would be a simple way to address
https://github.com/zhuowei/RaspberryJuice/issues/45

**Comment by martinohanlon** [comment]
Yes they would...  but if i make `.origin` 0,0,0 all coordinates become absolute and its a simpler implementation. Thats what I've done. Its tagged version 1.9, I'll get it released shortly.

**Comment by martinohanlon** [comment]
You may have noticed but 1.9 has been released including the changes. Thank you :)

**Pull request merged**
