### PR TITLE
add "hostname" option

### PR DESCRIPTION
**Pull request by neuhaus**
this added option improves security because now you can bind to localhost
and completely prevent remote access to the python API

### CODE REVIEW

**Comment by zhuowei** [comment]
Should the default bind address in the config.yml be localhost in the config file, or should it be empty/bind on all by default?

**Comment by neuhaus** [comment]
I changed the default hostname in the config file to "*"

**Comment by neuhaus** [comment]
Is there any reason why this new option cannot be merged?

**Comment by Marcinosoft** [comment]
I personally think it would be fine to add an option to allow bind listener to specified hostname. It could be usefull if someone want to bind it to localhost to prevent ohers from LAN to connect. It may be also useful when you want to bind it to specified network card only if multiple are present.

**Comment by martinohanlon** [comment]
Merging into dev branch to test

**Comment by martinohanlon** [comment]
I get an error when trying to launch RaspberryJuice.

```
[08:33:13 INFO]: [RaspberryJuice] Enabling RaspberryJuice v1.12.1
[08:33:13 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while scanning an alias
 in 'string', line 5, column 11:
    hostname: *
              ^
expected alphabetic or numeric character, but found
(10)
 in 'string', line 5, column 12:
    hostname: *
```

image

The full server startup script and error can be seen at https://pastebin.com/FXkseHae

@neuhaus any ideas?

**Comment by neuhaus** [comment]
Weird. I have to investigate.

**Comment by martinohanlon** [comment]
Thanks

The code base is in branch 1_12_1 https://github.com/zhuowei/RaspberryJuice/tree/1_12_1

If you send a PR could you base it on that branch pls.

**Pull request merged**
